apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-management
spec:
  templates:
  - name: create-new-pr
    inputs: 
      parameters: 
      - name: bitbucket-username
      - name: bitbucket-url
        value: bitbucket.org
      - name: workspace-name
      - name: repo-name
      - name: branch-name
      - name: file-path
        value: /folder/file/path.yaml
      - name: variable-path
        value: .common.image.name
      - name: image-name
      - name: new-image-tag
    script:
      image: greenopsinc/git
      command: [/bin/sh]
      env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: "bitbucket-secret"
              key: password
      source: |
        set -euo pipefail
        apk add yq
        git clone https://{{inputs.parameters.bitbucket-username}}:$PASSWORD@{{inputs.parameters.bitbucket-url}}/{{inputs.parameters.workspace-name}}/{{inputs.parameters.repo-name}}.git
        cd {{inputs.parameters.repo-name}}
        git checkout {{inputs.parameters.branch-name}}
        yq e -i '{{inputs.parameters.variable-path}} = "{{inputs.parameters.image-name}}:{{inputs.parameters.new-image-tag}}"' {{inputs.parameters.file-path}}
        git add {{inputs.parameters.file-path}}
        git config --global user.name "greenops"
        git config --global user.email "greenops@greenops.io"
        git commit -m "Updating image version to {{inputs.parameters.new-image-tag}}"
        git push --set-upstream origin {{inputs.parameters.branch-name}}
